// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Tapapies",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Tapapies",
            targets: ["AppModule"],
            bundleIdentifier: "eu.arifads.tapas",
            teamIdentifier: "YD7D2D6FJ4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sandwich),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationWhenInUse(purposeString: "Please")
            ],
            appCategory: "public.app-category.shopping"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("restaurants.json")
            ]
        )
    ]
)